### ISSUE TITLE
TypeError("NamedTemporaryFile() got an unexpected keyword argument 'errors'",)

### ISSUE THREAD

**Issue by markland556** [dizcza/hashcat-wpa-server#3]
Having an issue in a docker container. When a file is uploaded it will run for a moment then show this error under status

**Comment by dizcza** [comment]
Thanks for letting me know. I'll check it out.

I rarely use the UI though. I prefer the command mode interface. You can check it out till I fix the issue.

**Comment by markland556** [comment]
Ill give it a shot. In the meanwhile ive been trying to figure out when adding wordlist files to the appropriate folder the container runs wc on the file and loops. CPU usage is around 70-90% for that PID and usually only makes it to 20seconds of runtime before it restarts. It seems to be forcing gunicorn to restart as well thus making the web ui error out with a 503 from Nginx

**Comment by dizcza** [comment]
> Having an issue in a docker container. When a file is uploaded it will run for a moment then show this error under status

Please add the full traceback and describe how you uploaded the file or better make a screenshot. I cannot reproduce the issue.

**Comment by dizcza** [comment]
Ok thanks, I'll have a look. I imagine the issue could be that you use gunicorn while I typically run in a dev environment pure python. Gunicorn is preferred, so I need to double-check that.

**Comment by dizcza** [comment]
All right, the issue was in old python3.6 in the docker. I've migrated the docker part to use python3.9, this should fix the error you've shown. The `fast` wordlist mode is fixed also.

**Comment by dizcza** [comment]
You need to redownload the docker image WITHOUT CACHE. If you don't know how to redownload a docker image run `docker system prune --volumes -f` and then `docker pull dizcza/hashcat-wpa-server:latest` again, but it'll wipe all your docker images, containers, and volumes.

Please let me know if this worked for you.

**Comment by dizcza** [comment]
I've also refactored the status update of the profile page so now it should call the `wc` only once per file.
